/** Tous les textes de l'interface (français uniquement). */

const plural = (n: number, one: string, many: string): string => `${n} ${n > 1 ? many : one}`;

export const S = {
  appName: 'Cycle de force',
  loading: 'Chargement…',
  loadError: 'Impossible d’ouvrir la base de données locale.',
  saveError: 'L’enregistrement a échoué, rien n’a été modifié.',

  common: {
    cancel: 'Annuler',
    close: 'Fermer',
    next: 'Suivant',
    previous: 'Précédent',
    create: 'Créer',
    confirm: 'Confirmer',
    none: 'Aucun',
    /** Semaine du cycle (les numéros S0, S1… sont réservés à la vague de chaque modèle). */
    week: (n: number) => `Sem. ${n}`,
  },

  weekdays: ['Lundi', 'Mardi', 'Mercredi', 'Jeudi', 'Vendredi', 'Samedi', 'Dimanche'],
  weekdaysShort: ['L', 'M', 'M', 'J', 'V', 'S', 'D'],
  lifts: { S: 'Squat', B: 'Bench', D: 'Deadlift' },

  nav: {
    label: 'Navigation principale',
    calendar: 'Calendrier',
    today: 'Aujourd’hui',
    templates: 'Modèles',
    stats: 'Stats',
  },
  menu: {
    settings: 'Réglages',
    back: 'Retour',
  },

  sessionStatus: {
    PLANNED: 'Planifiée',
    MISSED: 'Manquée',
    IN_PROGRESS: 'En cours',
    FAILED: 'Échec',
    INCOMPLETE: 'Incomplète',
    VALIDATED: 'Validée',
  },

  calendar: {
    title: 'Calendrier',
    viewLabel: 'Affichage',
    month: 'Mois',
    week: 'Semaine',
    previous: 'Période précédente',
    next: 'Période suivante',
    today: 'Aujourd’hui',
    noSessions: 'Aucune séance',
    addSession: 'Ajouter une séance',
    addSessionOn: (day: string) => `Ajouter une séance le ${day}`,
    cycleBanner: (name: string, week: number, total: number) => `${name} · semaine ${week}/${total}`,
    noCycle: 'Aucun cycle en cours',
    actions: 'Actions du calendrier',
    daySessions: (n: number) => plural(n, 'séance', 'séances'),
  },

  example: {
    title: 'Bienvenue',
    text: 'Créer le cycle d’exemple « Bloc 0 » à partir de cette semaine ? 7 semaines, max S 170 / B 115 / D 210, Mar Deadlift · Jeu SBD · Sam Bench · Dim Squat.',
    create: 'Créer le Bloc 0',
    later: 'Plus tard',
  },

  sessionCard: {
    actions: (name: string) => `Actions sur la séance ${name}`,
    tonnage: 'Tonnage',
    empty: 'Aucun exercice',
  },

  sessionActions: {
    open: 'Ouvrir',
    move: 'Déplacer à une autre date',
    duplicate: 'Dupliquer à une autre date',
    delete: 'Supprimer',
    targetDate: 'Nouvelle date',
    confirmMove: 'Déplacer',
    confirmDuplicate: 'Dupliquer',
    confirmDelete: 'Des séries de cette séance sont déjà réalisées. Supprimer quand même ?',
    confirmDeleteButton: 'Supprimer définitivement',
    deleted: 'Séance supprimée',
    moved: (day: string) => `Séance déplacée au ${day}`,
    duplicated: (day: string) => `Séance dupliquée au ${day}`,
  },

  addSession: {
    title: (day: string) => `Ajouter une séance · ${day}`,
    template: 'Modèle',
    week: 'Semaine du modèle',
    weekShort: (n: number) => `Sem. ${n}`,
    inCycle: (name: string, week: number) => `Dans ${name}, semaine ${week}`,
    outOfCycle: 'Hors cycle',
    empty: 'Séance vide',
    emptyName: 'Séance libre',
    added: 'Séance ajoutée',
  },

  cycleForm: {
    newTitle: 'Nouveau cycle',
    steps: ['Cycle', 'Max', 'Planning', 'Aperçu'],
    stepOf: (i: number, n: number, label: string) => `Étape ${i}/${n} · ${label}`,
    name: 'Nom du cycle',
    defaultName: (n: number) => `Bloc ${n}`,
    startDate: 'Date de début',
    startsOn: (day: string) => `Le cycle commence le ${day}.`,
    weeks: 'Nombre de semaines',
    max: 'Max théoriques',
    maxHint: 'Base de tous les pourcentages du cycle.',
    planning: 'Planning hebdomadaire',
    noTemplate: '—',
    total: (n: number) => `${plural(n, 'séance sera créée', 'séances seront créées')}.`,
    weekLabel: (n: number) => `Sem. ${n}`,
    invalid: 'Vérifie le nom, la date et les max.',
    created: (name: string, n: number) => `${name} créé : ${plural(n, 'séance', 'séances')}`,
  },

  conflicts: {
    title: 'Jours déjà occupés',
    intro: 'Ces jours contiennent déjà une séance. Que faire ?',
    replace: 'Remplacer',
    add: 'Ajouter à côté',
    skip: 'Ignorer ce jour',
    all: 'Pour tous les jours',
    existing: (names: string) => `Déjà : ${names}`,
    unresolved: 'Choisis une option pour chaque jour.',
  },

  copyMode: {
    label: 'Contenu des séances',
    template: 'Reprendre la prescription du modèle',
    templateWeek: 'Semaine du modèle',
    asIs: 'Copier les séances telles quelles (avec mes modifications)',
    note: 'Les statuts et valeurs réalisées ne sont jamais copiés : tout repart en « prévu ».',
  },

  duplicateWeek: {
    title: 'Dupliquer une semaine',
    source: 'Semaine source',
    target: 'Semaine cible',
    weekOf: (range: string) => `Semaine du ${range}`,
    cycleWeek: (name: string, week: number) => `${name} · sem. ${week}`,
    outOfCycle: 'Hors cycle',
    found: (n: number) => plural(n, 'séance', 'séances'),
    none: 'Aucune séance dans cette semaine.',
    sameWeek: 'Choisis une semaine cible différente.',
    submit: 'Dupliquer la semaine',
    done: (n: number) => `${plural(n, 'séance créée', 'séances créées')}`,
  },

  duplicateCycle: {
    title: 'Dupliquer le cycle',
    name: 'Nom du nouveau cycle',
    defaultName: (name: string) => `${name} (suite)`,
    startDate: 'Date de début',
    max: 'Nouveaux max',
    bump: (kg: string) => `+${kg}`,
    reset: 'Max actuels',
    modeTemplate: 'Régénérer depuis les modèles',
    modeAsIs: 'Copier les séances telles quelles (avec mes modifications)',
    submit: 'Créer le cycle',
    notFound: 'Cycle introuvable.',
  },

  cycle: {
    title: 'Cycle',
    dates: (from: string, to: string) => `Du ${from} au ${to}`,
    currentWeek: (w: number, n: number) => `Semaine ${w}/${n}`,
    max: 'Max théoriques',
    planning: 'Planning',
    weeks: 'Semaines',
    weekRow: (w: number, range: string) => `Sem. ${w} · ${range}`,
    weekProgress: (done: number, total: number) => `${done}/${total} faites`,
    duplicate: 'Dupliquer le cycle',
    duplicateWeek: 'Dupliquer une semaine',
    duplicateThisWeek: (w: number) => `Dupliquer la semaine ${w}`,
    notFound: 'Cycle introuvable.',
  },

  session: {
    title: 'Séance',
    inCycle: (name: string, week: number) => `${name} · semaine ${week}`,
    outOfCycle: 'Hors cycle',
    empty: 'Aucun exercice dans cette séance.',
    toEnter: 'à saisir',
    notFound: 'Séance introuvable.',
    totals: 'Totaux de la séance',
    tonnage: 'Tonnage',
    reps: 'reps',
    kgPerRep: 'kg/rep',
    validateAll: 'Tout valider',
    validatedAll: (n: number) => plural(n, 'série validée', 'séries validées'),
    rir: 'RIR',
    rirOf: (name: string) => `RIR ${name}`,
    note: 'Note',
    exerciseNote: (name: string) => `Note ${name}`,
    sessionNote: 'Note de séance',
    edit: 'Modifier la séance',
    undo: 'Annuler',
    setValidated: 'Série validée',
    setReset: 'Série remise à prévu',
    setRecorded: (status: string) => `Série : ${status}`,
    setLabel: (i: number, text: string, rule: string, status: string) =>
      `Série ${i} : ${text}${rule ? `, ${rule}` : ''}, ${status}. Appui long pour plus d’options.`,
    planned: 'prévu',
  },

  setStatus: {
    PLANNED: 'Prévue',
    VALIDATED: 'Validé',
    FAILED: 'Échec',
    NOT_DONE: 'Non réalisé',
    CLUSTER: 'Cluster',
  },

  setSheet: {
    title: (i: number, name: string) => `Série ${i} · ${name}`,
    plannedWas: (text: string) => `Prévu : ${text}`,
    reps: 'Reps réalisées',
    kg: 'Charge réalisée',
    failed: 'Échec',
    cluster: 'Cluster',
    notDone: 'Non réalisé',
    validated: 'Validé',
    reset: 'Remettre à prévu',
  },

  edit: {
    done: 'Terminer',
    cancel: 'Annuler les modifications',
    sessionName: 'Nom de la séance',
    exerciseName: (i: number) => `Nom de l’exercice ${i}`,
    moveUp: (name: string) => `Monter ${name}`,
    moveDown: (name: string) => `Descendre ${name}`,
    removeExercise: (name: string) => `Supprimer ${name}`,
    addSet: 'Ajouter une série',
    removeSet: (i: number) => `Supprimer la série ${i}`,
    setReps: (i: number) => `Reps série ${i}`,
    setLoadKind: (i: number) => `Type de charge série ${i}`,
    setLoadValue: (i: number) => `Valeur de charge série ${i}`,
    setLift: (i: number) => `Mouvement série ${i}`,
    loadKinds: { FIXED: 'kg', PERCENT: '% max', BODYWEIGHT: 'PDC +', NONE: 'libre' },
    locked: 'Réalisée',
    addExercise: 'Ajouter un exercice',
    newExerciseName: 'Nom du nouvel exercice',
    add: 'Ajouter',
    duplicateExercise: 'Cet exercice est déjà dans la séance.',
    scopeTitle: 'Appliquer la modification',
    scopeThis: 'Cette séance uniquement',
    scopeFollowing: (n: number) => `Aussi les semaines suivantes de ce cycle (${plural(n, 'séance', 'séances')})`,
    scopeNote: 'Seules les séries encore prévues des séances suivantes sont modifiées.',
    saved: 'Séance modifiée',
    savedIn: (n: number) => `Modifié dans ${plural(n, 'séance', 'séances')}`,
  },

  max: {
    title: 'Mes max',
    edit: 'Modifier les max',
    sheetTitle: (cycle: string) => `Max · ${cycle}`,
    preview: (n: number) =>
      n === 0 ? 'Aucune série planifiée ne change.' : `${plural(n, 'série planifiée va changer', 'séries planifiées vont changer')}`,
    example: (name: string, from: string, to: string) => `${name} ${from} → ${to} kg`,
    doneNote: 'Les séries déjà réalisées gardent leur charge.',
    save: 'Enregistrer les max',
    saved: 'Max enregistrés',
    history: 'Historique',
    change: (lift: string, from: string, to: string, when: string) => `${when} · ${lift} ${from} → ${to} kg`,
  },

  backup: {
    title: 'Sauvegarde',
    last: (when: string) => `Dernière sauvegarde : ${when}`,
    never: 'Aucune sauvegarde pour l’instant.',
    export: 'Exporter une sauvegarde',
    exported: 'Sauvegarde exportée',
    shared: 'Sauvegarde partagée',
    reminderDays: 'Rappel si pas de sauvegarde depuis (jours)',
    restore: 'Restaurer une sauvegarde…',
    restoreTitle: 'Restaurer une sauvegarde',
    preview: (when: string) => `Sauvegarde du ${when}`,
    counts: (cycles: number, sessions: number, sets: number) =>
      `${plural(cycles, 'cycle', 'cycles')} · ${plural(sessions, 'séance', 'séances')} · ${plural(sets, 'série réalisée', 'séries réalisées')}`,
    migrated: (v: number) => `Fichier d’une ancienne version (${v}) : il sera converti.`,
    warning: 'Toutes les données actuelles seront remplacées. Une copie de l’état actuel est gardée et téléchargeable ci-dessous.',
    confirm: 'Remplacer toutes mes données',
    restored: 'Données restaurées',
    preRestore: 'Télécharger la copie d’avant restauration',
    errors: {
      NOT_JSON: 'Ce fichier n’est pas un JSON lisible.',
      WRONG_APP: 'Ce fichier ne vient pas de Cycle de force.',
      TOO_NEW: 'Cette sauvegarde vient d’une version plus récente de l’app : mets l’app à jour avant de la restaurer.',
      INVALID: 'Sauvegarde corrompue ou incomplète.',
    },
    reminder: (days: number | null) =>
      days === null ? 'Aucune sauvegarde de tes données pour l’instant.' : `Pas de sauvegarde depuis ${plural(days, 'jour', 'jours')}.`,
    saveNow: 'Sauvegarder maintenant',
  },

  today: {
    title: 'Aujourd’hui',
    noSession: 'Aucune séance aujourd’hui.',
    next: (day: string) => `Prochaine séance : ${day}`,
    toCalendar: 'Voir le calendrier',
  },
  templates: {
    title: 'Modèles de séance',
    native: 'Natif',
    custom: 'Perso',
    weeks: (n: number) => plural(n, 'semaine', 'semaines'),
    exercisesWeek1: (n: number) => `${plural(n, 'exercice', 'exercices')} en S1`,
    new: 'Nouveau modèle',
    newName: 'Nom du modèle',
    newWeeks: 'Nombre de semaines',
    create: 'Créer le modèle',
    created: (name: string) => `Modèle « ${name} » créé`,
  },

  templateEditor: {
    title: 'Modèle',
    name: 'Nom du modèle',
    color: 'Couleur',
    colorN: (i: number) => `Couleur ${i}`,
    weeks: 'Nombre de semaines',
    weekTabs: 'Semaines du cycle',
    weekTabsWave: 'Semaines du cycle · numéro de vague (S0 = deload)',
    weekTab: (n: number) => `Sem. ${n}`,
    deload: 'Semaine de deload (S0)',
    deloadNone: 'Aucune : pas de numéro de semaine',
    deloadHint: 'Les séances de ce modèle s’appellent « Nom S0 » la semaine de deload, puis S1, S2… jusqu’au test au RM.',
    copyWeek: (k: number) => `Copier la semaine ${k} vers…`,
    copyTargets: 'Semaines cibles',
    all: 'Toutes',
    copyApply: 'Copier',
    copied: (k: number, n: number) => `Semaine ${k} copiée vers ${plural(n, 'semaine', 'semaines')}`,
    progression: 'Appliquer une progression',
    progExercise: 'Exercice',
    progLift: 'En % du max',
    progFrom: 'De (%)',
    progTo: 'À (%)',
    progStep: 'Pas (%)',
    progWeeks: 'Semaines concernées',
    progNote:
      'Toutes les séries de l’exercice passent au pourcentage de la semaine. Une semaine sans l’exercice (deload) ne fait pas avancer la progression.',
    progAbsent: (w: number) => `Sem. ${w} deload`,
    progApply: 'Appliquer',
    progApplied: 'Progression appliquée',
    progSkipped: (weeks: string) => `Progression appliquée (deload en ${weeks})`,
    noExercises: 'Ajoute d’abord un exercice au modèle.',
    save: 'Enregistrer',
    saved: 'Modèle enregistré',
    unsaved: 'Modifications non enregistrées',
    discard: 'Annuler',
    more: 'Autres actions',
    duplicate: 'Dupliquer ce modèle',
    duplicateName: (name: string) => `${name} (copie)`,
    reset: 'Réinitialiser le modèle natif',
    resetConfirm: 'Remettre ce modèle comme à l’origine ? Tes modifications du modèle seront perdues ; les séances déjà créées ne changent pas.',
    resetDone: 'Modèle réinitialisé : enregistre pour confirmer.',
    delete: 'Supprimer ce modèle',
    deleteConfirm: 'Supprimer ce modèle ? Les séances déjà créées ne changent pas.',
    deleted: 'Modèle supprimé',
    confirm: 'Confirmer',
    updateFutureTitle: 'Mettre à jour les séances futures non commencées ?',
    updateFutureText: (n: number) =>
      `${plural(n, 'séance à venir utilise', 'séances à venir utilisent')} ce modèle et ${n > 1 ? 'ne sont pas commencées' : 'n’est pas commencée'}.`,
    updateYes: 'Mettre à jour ces séances',
    updateNo: 'Non, seulement le modèle',
    updated: (n: number) => `Modèle enregistré, ${plural(n, 'séance mise à jour', 'séances mises à jour')}`,
    notFound: 'Modèle introuvable.',
  },
  stats: {
    title: 'Stats',
    empty: 'Pas encore de séries réalisées : les graphiques se rempliront au fil des séances.',
    cycle: 'Cycle',
    showData: 'Voir les données',
    tileTonnage: 'Tonnage du cycle',
    tileSessions: 'Séances faites',
    tileSets: 'Séries réalisées',
    byWeek: 'Tonnage par semaine',
    bySession: 'Tonnage par séance',
    byCycle: 'Tonnage par cycle',
    exercise: 'Charge max et e1RM',
    exerciseSub: 'e1RM d’Epley, séries de 1 à 10 reps, tous cycles confondus',
    exerciseSelect: 'Exercice',
    noExercise: 'Aucun exercice avec des séries réalisées.',
    maxKg: 'Charge max',
    e1rm: 'e1RM',
    maxes: 'Max théoriques',
    maxesSub: 'Max de départ de chaque cycle, puis chaque changement',
    statuses: 'Statuts des séries',
    statusesSub: 'Séries réalisées, par cycle',
    planned: (n: number) => `${n} prévues`,
    volume: 'Volume par modèle',
    noTemplate: 'Sans modèle',
    sessionsN: (n: number) => plural(n, 'séance', 'séances'),
    colWeek: 'Semaine',
    colDate: 'Date',
    colSession: 'Séance',
    colCycle: 'Cycle',
    colTonnage: 'Tonnage (kg)',
    colSessions: 'Séances',
    colKg: 'kg',
  },
  settings: {
    title: 'Réglages',
    theme: 'Thème',
    themes: { dark: 'Sombre', light: 'Clair', system: 'Système' },
    rounding: 'Arrondi des charges',
    roundingNone: 'Aucun',
    storage: 'Stockage',
    storagePersisted: 'Stockage persistant accordé par le navigateur.',
    storageNotPersisted: 'Stockage non garanti : le navigateur peut effacer les données. Pense à sauvegarder.',
    storageUnknown: 'Statut du stockage inconnu.',
    version: (v: string) => `Version ${v}`,
  },
} as const;
